# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('maquina', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
