# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_accion', models.DateTimeField(verbose_name='Realizada el')),
            ],
        ),
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('estado', models.CharField(max_length=9)),
                ('elaboro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='accion',
            name='pendiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendientes.Pendiente'),
        ),
        migrations.AddField(
            model_name='accion',
            name='realizo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Persona'),
        ),
    ]
